interface ContractDetail{
    contractID : number,
    hostelName : string,
    hostelAddress : string,
    roomName : string,
    roomFee : number,
    roomDescription : string,
    depositFee : number,
    studentLeadAccountName : string,
    studentLeadPhone : string,
    studentLeadCitizen : string,
    ownerAccountName : string,
    ownerPhone : string,
    ownerCitizen : string,
    initWaterNumber : number,
    initElectricityNumber : number,
    contractTerm : string,
    createdDate : Date,
    dateSign : Date,
    dateStart : Date,
    dateEnd : Date,
    memberContract : MemberContract[],
    roomServiceDetails : ServiceRoomContract[],
    status : number
}